### PR TITLE
Devel/getters setters master

### PR DESCRIPTION
**Pull request by metelik**
Getter and setter functions for intrinsic reporting related properties

### CODE REVIEW

**Review by skarg — CHANGES_REQUESTED** [review]
Please run 'clang-format' on the code (at least the new code) so that it conforms to the library style. There is a .clang-format definition file in the root of the project.

**Comment by metelik** [comment]
> Please run 'clang-format' on the code (at least the new code) so that it conforms to the library style. There is a .clang-format definition file in the root of the project.

It looks much different ater running clang-format this time: 
image
 Do we want to do it? IMO there is not much wrong with the current code's formatting.

**Comment by skarg** [comment]
Having .clang-format is supposed to avoid 'opinions'.
ColumnLimit: 80 is exceeded on some lines.
clang-format doesn't make declaration tables pretty yet, so I often surround tables with `/* clang-format off */` and `/* clang-format on */` and manually format the table.
You could also just select the code that is changed and format selection only (in vscode it can be done), or hand format.

**Comment by skarg** [comment]
```
$ clang-format --version
clang-format version 16.0.4
```

**Comment by metelik** [comment]
> ```
> $ clang-format --version
> clang-format version 16.0.4
> ```

Ubuntu clang-format version 14.0.0-1ubuntu1.1

**Comment by metelik** [comment]
> Having .clang-format is supposed to avoid 'opinions'. ColumnLimit: 80 is exceeded on some lines. clang-format doesn't make declaration tables pretty yet, so I often surround tables with `/* clang-format off */` and `/* clang-format on */` and manually format the table. You could also just select the code that is changed and format selection only (in vscode it can be done), or hand format.

Aye - Ad limit of 80 - we are not in the times of 80x24 terminals anymore  but this is my unsolicited opinion.

I am kind of surprised it changing original scheme of

void function(...)
{
(...)
}

to:

void function(...) {
(...)
}

I am fine with both schools but I am non-less surprised on its decision making on coding style.

**Comment by skarg** [comment]
Not every developer has the luxury of wide screen all the time. I sometimes develop in a text only VM (i.e. FreeBSD) or more commonly on a notebook laptop, and having code that is longer than 80 columns is a problem when text is hidden.

**Comment by skarg** [comment]
Pulled the branch into bacnet-stack repo and fixed the formatting [#742]

**Comment by metelik** [comment]
> Pulled the branch into bacnet-stack repo and fixed the formatting [#742]

Muchas gracia senor :)

**Pull request closed without merging**
