### PR TITLE
Make all demo object variables static.

### PR DESCRIPTION
**Pull request by ralight**
This conflicts with #12, but also solves the same issue. If you prefer to merge #12 first, then I'm happy to update this PR to fix the conflict.

### CODE REVIEW

**Comment by ralight** [comment]
That's fixed now.

**Comment by GeertL** [comment]
What about `Object_List` in `netport.c`? That might be another candidate to make static.

**Comment by skarg** [comment]
The Travis build script was updated and caused check failures. You should be able to `git merge origin master` into your branch and push new changes to fix the checks for this pull request.

**Comment by ralight** [comment]
@GeertL thanks, well spotted.

I've added the final static variable and rebased against the latest master, so this should be ok again.

**Pull request merged**
